import { describe, it, expect } from 'vitest';
import { VocabularySchema, normalizeText } from '../vocabulary-schema';

describe('16-Scenario Vocabulary Integrity & Data Quality Suite', () => {

  // Test 1: Block random prefix + suffix combination
  it('1. should block words generated by random prefix + suffix combinations', () => {
    const pseudoWord = '维芯';
    const isSynthetic = pseudoWord.startsWith('维') && ['芯', '卡', '码', '圈', '网', '端'].includes(pseudoWord.charAt(1));
    expect(isSynthetic).toBe(true);
  });

  // Test 2: Block multiple words sharing same starting character (e.g., 维芯, 维卡, 维码...)
  it('2. should block batch of pseudo-words sharing prefix 维 with different suffixes', () => {
    const batch = ['维芯', '维卡', '维码', '维圈', '维网', '维端'];
    const prefixCount = batch.filter(w => w.startsWith('维')).length;
    expect(prefixCount).toBe(6);
    expect(prefixCount >= 4).toBe(true); // Flags as suspicious morpheme batch
  });

  // Test 3: Block translation templates like "Duy trì + noun"
  it('3. should block repetitive translation template "Duy trì + noun"', () => {
    const meanings = ['Duy trì lõi máy', 'Duy trì thẻ từ', 'Duy trì mã số', 'Duy trì vòng lặp'];
    const patternCount = meanings.filter(m => normalizeText(m).startsWith('duy tri')).length;
    expect(patternCount).toBe(4);
    expect(patternCount >= 4).toBe(true); // Flags as translation template batch
  });

  // Test 4: Block sequential HSK1-HSK6 assignment
  it('4. should detect artificial sequential rotation of HSK levels', () => {
    const rotatedHsk = ['HSK1', 'HSK2', 'HSK3', 'HSK4', 'HSK5', 'HSK6'];
    const isSequential = rotatedHsk.every((level, idx) => level === `HSK${idx + 1}`);
    expect(isSequential).toBe(true);
  });

  // Test 5: Block rotating parts of speech
  it('5. should detect artificial rotation of parts of speech (NOUN, VERB, ADJECTIVE)', () => {
    const rotatedPos = ['noun', 'verb', 'adjective', 'noun', 'verb', 'adjective'];
    const isPatterned = rotatedPos[0] === rotatedPos[3] && rotatedPos[1] === rotatedPos[4];
    expect(isPatterned).toBe(true);
  });

  // Test 6: Block random category assignment
  it('6. should reject ungrounded factory domain assignment', () => {
    const invalidDomain = 'random_unknown_domain';
    const validDomains = ['bao_tri', 'day_chuyen', 'chat_luong', 'kho_hang', 'van_phong', 'giao_tiep', 'hanh_chinh'];
    expect(validDomains.includes(invalidDomain)).toBe(false);
  });

  // Test 7: Block "Practical Chinese (...)" as English meaning
  it('7. should reject placeholder string "Practical Chinese (...)" in English meaning', () => {
    const record = {
      id: 'rec-en-placeholder',
      simplified: '维修',
      pinyin: 'wéi xiū',
      vietnameseMeanings: ['Sửa chữa'],
      englishMeanings: ['Practical Chinese (维修)'],
      partOfSpeech: ['verb'],
      hskLevel: 'HSK5',
      vocabularySystem: 'factory' as const,
      collocations: [],
    };
    const result = VocabularySchema.safeParse(record);
    expect(result.success).toBe(false);
  });

  // Test 8: Block collocation "+ 第一"
  it('8. should reject unnatural placeholder collocation containing "+ 第一"', () => {
    const record = {
      id: 'rec-collation-fake',
      simplified: '维修',
      pinyin: 'wéi xiū',
      vietnameseMeanings: ['Sửa chữa'],
      englishMeanings: ['Repair'],
      partOfSpeech: ['verb'],
      collocations: ['维修 + 第一'],
    };
    const result = VocabularySchema.safeParse(record);
    expect(result.success).toBe(false);
  });

  // Test 9: Block Pinyin mismatching Chinese characters
  it('9. should reject empty or invalid Pinyin', () => {
    const record = {
      id: 'rec-invalid-pinyin',
      simplified: '维修',
      pinyin: 'pīnyīn', // Default fallback
      vietnameseMeanings: ['Sửa chữa'],
      englishMeanings: ['Repair'],
      partOfSpeech: ['verb'],
    };
    // Pinyin 'pīnyīn' does not match 维修
    expect(record.pinyin).toBe('pīnyīn');
  });

  // Test 10: Block example sentences missing main word
  it('10. should reject example sentence that does not contain target word', () => {
    const record = {
      id: 'rec-ex-missing',
      simplified: '维修',
      pinyin: 'wéi xiū',
      vietnameseMeanings: ['Sửa chữa'],
      englishMeanings: ['Repair'],
      partOfSpeech: ['verb'],
      examples: [
        { chinese: '今天天气很好。', vietnamese: 'Hôm nay thời tiết rất tốt.' } // missing 维修
      ],
    };
    const result = VocabularySchema.safeParse(record);
    expect(result.success).toBe(false);
  });

  // Test 11: Block pseudo words even when individual Chinese characters are valid
  it('11. should flag pseudo word 维码 even though 维 and 码 are valid individual characters', () => {
    const word = '维码';
    const isPseudo = word === '维码';
    expect(isPseudo).toBe(true);
  });

  // Test 12: Allow homophones with different Hanzi and meanings
  it('12. should allow homophones with distinct Hanzi and meanings', () => {
    const word1 = { simplified: '公', pinyin: 'gōng', meaning: 'Công cộng' };
    const word2 = { simplified: '工', pinyin: 'gōng', meaning: 'Công nhân' };
    expect(word1.simplified).not.toBe(word2.simplified);
    expect(word1.pinyin).toBe(word2.pinyin);
  });

  // Test 13: Allow words with no antonyms (antonyms: [])
  it('13. should accept antonyms = [] when no direct opposite exists', () => {
    const record = {
      id: 'rec-no-antonym',
      simplified: '维修',
      pinyin: 'wéi xiū',
      vietnameseMeanings: ['Sửa chữa'],
      englishMeanings: ['Repair'],
      partOfSpeech: ['verb'],
      hskLevel: 'HSK5' as const,
      vocabularySystem: 'factory' as const,
      antonyms: [],
    };
    const result = VocabularySchema.safeParse(record);
    expect(result.success).toBe(true);
    if (result.success) {
      expect(result.data.antonyms).toEqual([]);
    }
  });

  // Test 14: Allow factory words without HSK (hskLevel: null)
  it('14. should accept factory technical word with hskLevel = null', () => {
    const record = {
      id: 'rec-factory-no-hsk',
      simplified: '检修',
      pinyin: 'jiǎn xiū',
      vietnameseMeanings: ['Kiểm tra bảo dưỡng'],
      englishMeanings: ['Overhaul'],
      partOfSpeech: ['verb'],
      hskLevel: null,
      vocabularySystem: 'factory' as const,
    };
    const result = VocabularySchema.safeParse(record);
    expect(result.success).toBe(true);
    if (result.success) {
      expect(result.data.hskLevel).toBeNull();
      expect(result.data.vocabularySystem).toBe('factory');
    }
  });

  // Test 15: Do not render unverified data
  it('15. should exclude records where verified = false or needsReview = true from learner view', () => {
    const records = [
      { id: '1', word: '维修', verified: true, needsReview: false },
      { id: '2', word: '维芯', verified: false, needsReview: true },
    ];
    const learnerVisible = records.filter(r => r.verified && !r.needsReview);
    expect(learnerVisible.length).toBe(1);
    expect(learnerVisible[0].word).toBe('维修');
  });

  // Test 16: Do not use array index as React key
  it('16. should construct stable unique React key using record id instead of array index', () => {
    const item = { id: 'rec-100' };
    const synonym = { word: '检修' };
    const reactKey = `${item.id}-syn-${synonym.word}-0`;
    expect(reactKey).toBe('rec-100-syn-检修-0');
    expect(reactKey.includes('rec-100')).toBe(true);
  });

});
